/**
* @description constant file to store urls of api
*/
/**
 *routing based constants
 * */
export const Url = {
    signIn: '/users',
    generateAccessToken: '/Tokens/GetAuthorizationToken',
    reGenerateAccessToken: '/Tokens/GetAuthorizationToken',
    isExistingUser: '/users/Get',
    getProductTypes: '/producttypes',
    serviceRequestWizard: '/forms/7',
    getDivisions: '/Divisions',
    getMarks: '/marks',
    saveCustomerDetails: '/users',
    getCountries: '/Countries',
    getServiceTypes: '/serviceTypes',
    getStandards: '/standards',
    getExchangeRates: '/exchangerates',
    getUsers: '/users',
    getSemanticTags: '/semanticTags',
    getClauses: '/clauses',
    getTemplates: '/templates',
    getSections: '/sections',
    getSubSections: '/subSections',
    saveProductTypes: '/productTypes',
    saveStandard: '/standards',
    updateStandard: '/standards',
    saveProduct: '/productTypes',
    updateSemanticTag: '/semanticTags',
    saveSemanticTag: '/semanticTags',
    updateClause: '/clauses',
    updateSection: '/sections',
    updateTemplate: '/templates',
    updateSubSection: '/subSections',
    getDataTypes: '/dataTypes',
    getTemplateEditor: '/forms',
    getServiceOfferings: '/serviceOfferings',
    getDeliverables: '/deliverables',
    getPricingMultipliers: '/pricingMultipliers',
    saveServiceOfferings: '/serviceOfferings',
    updateServiceOfferings: '/serviceOfferings',
    saveDeliverables: '/Deliverables',
    updateDeliverables: '/Deliverables',
    savePricingMultipliers: '/pricingMultipliers',
    updatePricingMultipliers: '/pricingMultipliers',
    saveClause: '/clauses',
    saveSection: '/sections',
    saveTemplate: '/templates',
    saveSubSection: '/subSections',
    updateOrdinals: '/ordinals',
    getLabs: '/Labs',
    saveLabs: '/labs',
    updateLabs: '/labs',
    getCities: '/Cities',
    getGoverningDistricts: '/GoverningDistricts',
    getPostalCodes: '/PostalCodes',
    getAddress: '/Address',
    saveAddress: '/Address',
    updateAddress: '/Address',
    getCapabilities: '/Capabilities',
    saveCapabilities: '/capabilities',
    updateCapabilities: '/capabilities',
    getApiActions: '/ApiActions',
    getSurveyCreator: '/surverytemplates',
    updateSurveyCreator: '/surverytemplates',
    saveSurveyCreator: '/surverytemplates',
};
//# sourceMappingURL=urlConstants.js.map